In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('D:\\EduNet\\NSTI_Indore25_26\\ML\\Datasets\\Student_Performance.csv')
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [21]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({
    "Yes":1,
    "No":0
})
df

C:\Users\Jash\AppData\Local\Temp\ipykernel_32068\4108796942.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [22]:
df.describe()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,0.494800,6.530600,4.583300,55.224800
std,2.589309,17.343152,0.499998,1.695863,2.867348,19.212558
min,1.000000,40.000000,0.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,0.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,0.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,1.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,1.000000,9.000000,9.000000,100.000000

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X = df.drop(['Performance Index'],axis=1)
y = df['Performance Index']

In [25]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,random_state=42)

In [26]:
import tensorflow as tf

In [27]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(xtrain.shape[1],))
])

c:\Users\Jash\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

In [29]:

model.fit(xtrain, ytrain, epochs=50, batch_size=32)

Epoch 1/50

235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 913us/step - loss: 3782.6150 - mae: 57.5713
Epoch 2/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1934.7516 - mae: 40.0540
Epoch 3/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 906.1278 - mae: 26.2498
Epoch 4/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - loss: 402.1398 - mae: 16.5987
Epoch 5/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 192.9748 - mae: 11.2857
Epoch 6/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 120.8214 - mae: 9.0311
Epoch 7/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 100.0731 - mae: 8.2556
Epoch 8/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 94.5218 - mae: 8.0108
Epoch 9/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - loss: 92.4189 - mae: 7.9144
Epoch 10/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - loss: 90.7539 - mae: 7.8379
Epoch 11/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 89.0096 - mae: 7.7616
Epoch 12/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - loss: 87.1174 - mae: 7.6765
Epoch 13/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - loss: 85.0939 - mae: 7.5879
Epoch 14/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - loss: 82.9240 - mae: 7.4894
Epoch 15/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - loss: 80.6203 - mae: 7.3832
Epoch 16/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - loss: 78.1942 - mae: 7.2699
Epoch 17/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - loss: 75.6639 - mae: 7.1508
Epoch 18/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 73.0316 - mae: 7.0237
Epoch 19/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 70.3693 - mae: 6.8925
Epoch 20/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - loss: 67.6442 - mae: 6.7548
Epoch 21/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - loss: 64.8710 - mae: 6.6114
Epoch 22/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 62.1465 - mae: 6.4694
Epoch 23/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - loss: 59.4618 - mae: 6.3273
Epoch 24/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 56.8105 - mae: 6.1779
Epoch 25/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 761us/step - loss: 54.2180 - mae: 6.0310
Epoch 26/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - loss: 51.7652 - mae: 5.8870
Epoch 27/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 49.4097 - mae: 5.7478
Epoch 28/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - loss: 47.1912 - mae: 5.6119
Epoch 29/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - loss: 45.1236 - mae: 5.4774
Epoch 30/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step - loss: 43.1923 - mae: 5.3555
Epoch 31/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - loss: 41.4407 - mae: 5.2373
Epoch 32/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - loss: 39.7844 - mae: 5.1276
Epoch 33/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - loss: 38.3180 - mae: 5.0271
Epoch 34/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - loss: 36.9949 - mae: 4.9339
Epoch 35/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - loss: 35.7692 - mae: 4.8465
Epoch 36/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - loss: 34.7454 - mae: 4.7692
Epoch 37/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 783us/step - loss: 33.7536 - mae: 4.6975
Epoch 38/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - loss: 32.9776 - mae: 4.6460
Epoch 39/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - loss: 32.2347 - mae: 4.5864
Epoch 40/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - loss: 31.6241 - mae: 4.5411
Epoch 41/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - loss: 31.0296 - mae: 4.4957
Epoch 42/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - loss: 30.5460 - mae: 4.4574
Epoch 43/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - loss: 30.1269 - mae: 4.4266
Epoch 44/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - loss: 29.7061 - mae: 4.3938
Epoch 45/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 29.3831 - mae: 4.3698
Epoch 46/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - loss: 29.0206 - mae: 4.3409
Epoch 47/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 28.7372 - mae: 4.3191
Epoch 48/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - loss: 28.4629 - mae: 4.2995
Epoch 49/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - loss: 28.1785 - mae: 4.2770
Epoch 50/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 27.9161 - mae: 4.2565

In [30]:

loss, mae = model.evaluate(xtest, ytest)

print("\nTest MSE:", loss)
print("Test MAE:", mae)

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.4104 - mae: 4.3632

Test MSE: 29.410444259643555
Test MAE: 4.363206386566162