In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('D:\\EduNet\\NSTI_Indore25_26\\ML\\Datasets\\Student_Performance.csv')
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [3]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({
    "Yes":1,
    "No":0
})
df

C:\Users\Jash\AppData\Local\Temp\ipykernel_31580\4108796942.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Extracurricular Activities'] = df['Extracurricular Activities'].replace({

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [4]:
df.describe()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,0.494800,6.530600,4.583300,55.224800
std,2.589309,17.343152,0.499998,1.695863,2.867348,19.212558
min,1.000000,40.000000,0.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,0.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,0.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,1.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,1.000000,9.000000,9.000000,100.000000

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop(['Performance Index'],axis=1)
y = df['Performance Index']

In [7]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,random_state=42)

In [8]:
import tensorflow as tf

In [9]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(xtrain.shape[1],))
])

c:\Users\Jash\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
xtrain.shape[1]

5

In [10]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [11]:

model.fit(xtrain, ytrain, epochs=50, batch_size=32)

Epoch 1/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 6797.9663 - mae: 77.8000
Epoch 2/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - loss: 4106.3774 - mae: 59.5767
Epoch 3/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - loss: 2343.7415 - mae: 43.8289
Epoch 4/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1263.8772 - mae: 30.9202
Epoch 5/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 655.9910 - mae: 21.2928
Epoch 6/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 347.4234 - mae: 15.1601
Epoch 7/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - loss: 209.1863 - mae: 11.9014
Epoch 8/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - loss: 154.9138 - mae: 10.4112
Epoch 9/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 135.8195 - mae: 9.7900
Epoch 10/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 129.0143 - mae: 9.5285
Epoch 11/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - loss: 125.4139 - mae: 9.3780
Epoch 12/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 122.3836 - mae: 9.2567
Epoch 13/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 119.2775 - mae: 9.1318
Epoch 14/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 115.9612 - mae: 9.0075
Epoch 15/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 112.4224 - mae: 8.8672
Epoch 16/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 108.6862 - mae: 8.7186
Epoch 17/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - loss: 104.7594 - mae: 8.5621
Epoch 18/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - loss: 100.6872 - mae: 8.3921
Epoch 19/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - loss: 96.4711 - mae: 8.2104
Epoch 20/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - loss: 92.1815 - mae: 8.0283
Epoch 21/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - loss: 87.8388 - mae: 7.8326
Epoch 22/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 83.5095 - mae: 7.6338
Epoch 23/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 79.1689 - mae: 7.4228
Epoch 24/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 74.9952 - mae: 7.2291
Epoch 25/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 70.8917 - mae: 7.0182
Epoch 26/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 66.9753 - mae: 6.8109
Epoch 27/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 63.2576 - mae: 6.6091
Epoch 28/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 59.7606 - mae: 6.4124
Epoch 29/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 56.4964 - mae: 6.2262
Epoch 30/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 53.4770 - mae: 6.0416
Epoch 31/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50.7317 - mae: 5.8736
Epoch 32/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48.1901 - mae: 5.7119
Epoch 33/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 45.9204 - mae: 5.5627
Epoch 34/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 43.8058 - mae: 5.4222
Epoch 35/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 41.9236 - mae: 5.2930
Epoch 36/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - loss: 40.1861 - mae: 5.1720
Epoch 37/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 38.6806 - mae: 5.0670
Epoch 38/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 37.2909 - mae: 4.9611
Epoch 39/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 36.0533 - mae: 4.8746
Epoch 40/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - loss: 34.9909 - mae: 4.7949
Epoch 41/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - loss: 34.0261 - mae: 4.7244
Epoch 42/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 33.1761 - mae: 4.6583
Epoch 43/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - loss: 32.4479 - mae: 4.6032
Epoch 44/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - loss: 31.7994 - mae: 4.5551
Epoch 45/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - loss: 31.2249 - mae: 4.5105
Epoch 46/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - loss: 30.7024 - mae: 4.4694
Epoch 47/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - loss: 30.2528 - mae: 4.4346
Epoch 48/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 29.8680 - mae: 4.4055
Epoch 49/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - loss: 29.5158 - mae: 4.3798
Epoch 50/50
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - loss: 29.1695 - mae: 4.3516

In [12]:

loss, mae = model.evaluate(xtest, ytest)

print("\nTest MSE:", loss)
print("Test MAE:", mae)

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 30.5856 - mae: 4.4499

Test MSE: 30.585599899291992
Test MAE: 4.449884414672852

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 20 (84.00 B)

 Trainable params: 6 (24.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 14 (60.00 B)